const baseApi = "http://www.baqala-app.com/baqala-system/public/api/";
String token  = "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC93d3cuYmFxYWxhLWFwcC5jb21cL2JhcWFsYS1zeXN0ZW1cL3B1YmxpY1wvYXBpXC9sb2dpbiIsImlhdCI6MTY0Mjg2NzUwNiwibmJmIjoxNjQyODY3NTA2LCJqdGkiOiJGUFBjRTA0M3gwMUY5NXdYIiwic3ViIjo1OSwicHJ2IjoiMjNiZDVjODk0OWY2MDBhZGIzOWU3MDFjNDAwODcyZGI3YTU5NzZmNyJ9.rw8OHgyEuoAL7e6TZoguvoODjkclTpR9kLEEK4Hdi4o";

